### ISSUE TITLE
[Bug] - Black screens with drag.

### ISSUE THREAD

**Issue by luci1927** [eversoft-lk/discounts-lk#13]
### **Bug Report** @ChathuraSudaraka 

Appears black screens under top and bottom in Sign In and Sign Up pages..

![Image 1](https://github.com/user-attachments/assets/a674b608-4882-485d-96b6-0927caf6ad17)

![Image 2](https://github.com/user-attachments/assets/c6e4377e-db58-4505-aeb8-6db3610d7a9a)

**Comment by ChathuraSudaraka** [comment]
This issue has a ScrollView component and this issue only have IOS devices 📱. So i will fix it don't worry about that 🥱🙂‍↔️
